# Generated by Django 4.2.11 on 2024-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_category_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='categories',
            field=models.ManyToManyField(blank=True, null=True, to='main_app.category'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='rep',
            name='rep_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date & time:'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time spent (mins):'),
        ),
    ]
