# Generated by Django 4.2.11 on 2024-03-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_rep_categories_alter_rep_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='color',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
