# Generated by Django 4.2.11 on 2024-03-06 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_category_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rep',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main_app.category'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='rep_date_time',
            field=models.DateField(blank=True, null=True, verbose_name='Date & time:'),
        ),
    ]
