# Generated by Django 4.2.11 on 2024-03-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_rep_categories_alter_rep_rep_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name (required):'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name (required):'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='rep_date_time',
            field=models.DateField(blank=True, null=True, verbose_name='Date:'),
        ),
    ]
