# Generated by Django 4.2.11 on 2024-03-07 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_category_name_alter_rep_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('rep', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_app.rep')),
            ],
        ),
    ]
