# Generated by Django 4.2.11 on 2024-03-08 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_alter_category_name_alter_rep_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name (required)'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='categories',
            field=models.ManyToManyField(blank=True, to='main_app.category', verbose_name='Categories (multiples allowed)'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Title (required)'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='rep_date_time',
            field=models.DateField(blank=True, null=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='rep',
            name='time_spent',
            field=models.IntegerField(blank=True, null=True, verbose_name='Time spent (mins)'),
        ),
    ]
